[project]
name = "ComfyUI-Usgromana-Gallery"
description = "A comprehensive image gallery extension for ComfyUI that provides advanced image management, metadata editing, NSFW content filtering, real-time file monitoring, and a full-featured file explorer."
version = "1.1.5"
license = {file = "LICENSE"} 

dependencies = ["watchdog>=3.0.0"]

[project.urls]
Repository = "https://github.com/DayMan84/ComfyUI-Usgromana-Gallery"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/DayMan84/ComfyUI-Usgromana-Gallery/wiki"
"Bug Tracker" = "https://github.com/DayMan84/ComfyUI-Usgromana-Gallery/issues"

[tool.comfy]
PublisherId = "dayman84"
DisplayName = "ComfyUI-Usgromana-Gallery"
Icon = "https://raw.githubusercontent.com/DayMan84/ComfyUI-Usgromana-Gallery/refs/heads/main/web/assets/dark_logo_transparent.png"
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
